version: '2'

services:
    nginx:
        build: nginx
        volumes:
            - /etc/nginx/conf.d
            - ./certs:/etc/nginx/certs
        networks:
            - default
            - sherpa_default
        ports:
            - "80:80"
            - "443:443"
        restart: always

    dockergen:
        build: dockergen
        volumes_from:
            - nginx
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - /etc/nginx/certs
        networks:
            - default
            - sherpa_default
        command: >
            -notify-sighup dockerproxy_nginx_1
            -watch -only-published
            /etc/docker-gen/templates/nginx.tmpl
            /etc/nginx/conf.d/default.conf
        restart: always

networks:
    sherpa_default:
        external: true
